/** All 58 former HTML screens. IDs are resolved separately through authorized APIs. */
export const legacyRoutes: Record<string, string> = {
  'index.html': '/',
  '404.html': '*',
  'admin-dashboard.html': '/admin/revenue',
  'admin-expert-applications.html': '/admin/expert-applications',
  'admin-fee-config.html': '/admin/fee-config',
  'admin-revenue.html': '/admin/revenue',
  'analytics.html': '/client/analytics',
  'browse-tasks.html': '/worker/browse',
  'client-audit-offers.html': '/client/audit-offers',
  'client-dashboard.html': '/client/dashboard',
  'client-my-projects.html': '/client/projects',
  'client-wallet.html': '/client/wallet',
  'compliance-dashboard.html': '/admin/compliance',
  'dispute.html': '/project/:projectId/milestones/:milestoneId/disputes/new',
  'expert-audit-preview.html': '/expert/audit-preview/:id',
  'expert-audit-requests.html': '/expert/audit-requests',
  'expert-dashboard.html': '/expert/dashboard',
  'expert-dispute-cases.html': '/expert/disputes',
  'expert-landing.html': '/expert-landing',
  'expert-login.html': '/expert-login',
  'expert-messages.html': '/expert/messages',
  'expert-report-audit.html': '/expert/report-audit/:id',
  'expert-report-dispute.html': '/expert/report-dispute/:id',
  'expert-reports.html': '/expert/reports',
  'expert-settings.html': '/settings/expert',
  'expert-signup.html': '/expert-signup',
  'forgot-password.html': '/forgot-password',
  'hire-gig-workers.html': '/client/hire',
  'login.html': '/login',
  'messages.html': '/shared/messages',
  'milestone-reports.html': '/shared/reports',
  'my-proposals.html': '/worker/proposals',
  'performance-analytics.html': '/worker/analytics',
  'post-task.html': '/client/post-task',
  'profile-settings.html': '/settings/profile',
  'project-milestone-board.html': '/project/:id/milestone-board',
  'project-workroom.html': '/project/:id/workroom',
  'resolve-dispute.html': '/dispute/:id/resolve',
  'review-deliverable.html':
    '/project/:projectId/milestones/:milestoneId/review',
  'signup.html': '/signup',
  'staff-settings.html': '/settings/staff',
  'submit-deliverable.html':
    '/project/:projectId/milestones/:milestoneId/submit',
  'superuser-create-task.html': '/superuser/create-task',
  'superuser-dashboard.html': '/superuser/dashboard',
  'superuser-disputes.html': '/superuser/disputes',
  'superuser-escrow.html': '/superuser/escrow',
  'superuser-expert-applications.html': '/admin/expert-applications',
  'superuser-tasks.html': '/superuser/tasks',
  'superuser-users.html': '/superuser/users',
  'task-details.html': '/tasks/:id',
  'worker-applications.html': '/client/applications',
  'worker-dashboard.html': '/worker/dashboard',
  'worker-invitations.html': '/worker/invitations',
  'worker-milestone-board.html': '/project/:id/milestone-board',
  'worker-my-projects.html': '/worker/projects',
  'worker-settings.html': '/settings/worker',
  'worker-wallet.html': '/worker/wallet',
  'worker-workroom.html': '/project/:id/workroom',
};
export function legacyFile(pathname: string): string | undefined {
  if (pathname === '/index.html') return 'index.html';
  return /^\/pages\/([a-z0-9-]+\.html)$/.exec(pathname)?.[1];
}
