/**
 * Every page of the original app: URL name, <title>, and the role guard the
 * page ran first (Auth.requireRole). Generated from front-end/; keep in step.
 */
export const PAGES = {
  "404": { title: "404 — Page Not Found · Lannent", roles: null },
  "admin-dashboard": { title: "Admin Dashboard — Lannent", roles: ["revenue-admin"] },
  "admin-expert-applications": { title: "Expert Applications — Lannent Admin", roles: ["intake-admin", "compliance-admin"] },
  "admin-fee-config": { title: "Fee Configuration — Lannent", roles: ["revenue-admin"] },
  "admin-revenue": { title: "Revenue — Lannent", roles: ["revenue-admin", "compliance-admin"] },
  "analytics": { title: "Project Insights — Lannent", roles: ["client"] },
  "browse-tasks": { title: "Browse Tasks — Lannent", roles: ["worker"] },
  "client-audit-offers": { title: "Audit Offers — Lannent", roles: ["client"] },
  "client-dashboard": { title: "Client Dashboard — Lannent", roles: ["client"] },
  "client-my-projects": { title: "My Projects — Lannent", roles: ["client"] },
  "client-wallet": { title: "Wallet & Escrow — Lannent", roles: ["client"] },
  "compliance-dashboard": { title: "Audit Log — Lannent", roles: ["compliance-admin"] },
  "dispute": { title: "Raise Dispute — Lannent", roles: ["client", "worker"] },
  "expert-audit-preview": { title: "Review Before Accepting — Lannent", roles: ["expert"] },
  "expert-audit-requests": { title: "Audit Requests — Lannent", roles: ["expert"] },
  "expert-dashboard": { title: "Expert Dashboard — Lannent", roles: ["expert"] },
  "expert-dispute-cases": { title: "Dispute Cases — Lannent", roles: ["expert"] },
  "expert-landing": { title: "Expert Reviewer — GigBoard", roles: null },
  "expert-login": { title: "Expert Reviewer Login — GigBoard", roles: null },
  "expert-messages": { title: "Messages — Lannent Expert", roles: ["expert"] },
  "expert-report-audit": { title: "Technical Audit Report — Lannent", roles: ["expert", "client", "worker"] },
  "expert-report-dispute": { title: "Dispute Resolution Report — Lannent", roles: ["expert", "client", "worker"] },
  "expert-reports": { title: "Reports — Lannent", roles: ["expert"] },
  "expert-settings": { title: "Expert Settings — Lannent", roles: ["expert"] },
  "expert-signup": { title: "Apply as Expert Reviewer — Lannent", roles: null },
  "forgot-password": { title: "Reset Password — Lannent", roles: null },
  "hire-gig-workers": { title: "Hire Gig Workers — Lannent", roles: ["client"] },
  "login": { title: "Login — Lannent", roles: null },
  "messages": { title: "Messages — Lannent", roles: ["client", "worker", "expert"] },
  "milestone-reports": { title: "Milestone Reports — Lannent", roles: ["client", "worker", "expert"] },
  "my-proposals": { title: "My Proposals — Lannent", roles: ["worker"] },
  "performance-analytics": { title: "Performance Analytics — Lannent", roles: ["worker"] },
  "post-task": { title: "Post New Task — Lannent", roles: ["client"] },
  "profile-settings": { title: "Account Settings — Lannent", roles: ["client"] },
  "project-milestone-board": { title: "Milestone Board — Lannent", roles: ["client"] },
  "project-workroom": { title: "Project Workroom — Lannent", roles: ["client", "worker"] },
  "resolve-dispute": { title: "Resolve Dispute — Lannent", roles: ["expert"] },
  "review-deliverable": { title: "Review Deliverable — Lannent", roles: ["client", "expert"] },
  "signup": { title: "Sign Up — Lannent", roles: null },
  "staff-settings": { title: "Settings — Lannent", roles: ["superuser", "revenue-admin", "intake-admin", "compliance-admin"] },
  "submit-deliverable": { title: "Submit Deliverable — Lannent", roles: ["worker"] },
  "superuser-create-task": { title: "Create Task — Super User — Lannent", roles: null },
  "superuser-dashboard": { title: "Super User Dashboard — Lannent", roles: ["superuser"] },
  "superuser-disputes": { title: "All Disputes — Lannent", roles: null },
  "superuser-escrow": { title: "Escrow & Finance — Lannent", roles: ["superuser"] },
  "superuser-expert-applications": { title: "Expert Applications — Lannent Admin", roles: ["superuser"] },
  "superuser-tasks": { title: "Manage Tasks — Lannent", roles: ["superuser"] },
  "superuser-users": { title: "Manage Users — Lannent", roles: ["superuser"] },
  "task-details": { title: "Task Details — Lannent", roles: ["client", "worker"] },
  "worker-applications": { title: "Worker Applications — Lannent", roles: ["client"] },
  "worker-dashboard": { title: "Worker Dashboard — Lannent", roles: ["worker"] },
  "worker-invitations": { title: "Invitations — Lannent", roles: ["worker"] },
  "worker-milestone-board": { title: "Milestone Board — Lannent", roles: ["worker"] },
  "worker-my-projects": { title: "My Projects — Lannent", roles: ["worker"] },
  "worker-settings": { title: "Account Settings — Lannent", roles: ["worker"] },
  "worker-wallet": { title: "Worker Wallet — Lannent", roles: ["worker"] },
  "worker-workroom": { title: "Worker Workroom — Lannent", roles: ["worker"] },
  "index": { title: "Lannent — Trusted Collaboration for Freelance Projects", roles: null },
};
